Rates statistic
BitBotFactory/poloniexlendingbot pull request #647
Opened 2019-06-17 06:42 UTC by maroun2

## Description
It adds a plugin with rates statistic. It seems that someone wants this future also #312
It's my first pull request, so please excuse my mistakes.
Preview: https://ibb.co/TPKM8ZJ

## TESTING STAGE
It was tested. This functionality is separated from lending functionality. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [x] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

2019-06-25 01:30 UTC, Evanito commented
Currently: chart is based on the 24 hour schedule with multiple days stacked over each other.

This is useful if you are trying to look at the rates at certain times of day, otherwise I think it would be better to see the days linked end to end so you can see historical rates.

Maybe include a toggle between the modes or just set the default to the more intuitive mode (historical.)

2019-12-31 07:27 UTC, hajdbo commented on plugins/Rates.py
> +                if btc_offer > 1 and gap_botom_offer == 0:
btc_offer is never > 0

2021-03-22 12:12 UTC, SloRunner requested changes

2021-03-22 12:12 UTC, SloRunner commented on plugins/Rates.py
> +            for row in file_data[currency]:
fails if there is no file, fixable by commenting and un commenting, so maybe add
`if len(file_data[currency]) > 0:`

2021-03-24 12:27 UTC, SloRunner commented on plugins/Rates.py
> +            for row in file_data[currency]:
```suggestion
            if file_data:
              for row in file_data[currency]:
```

Tested and works as expected, else you get KeyError

2023-10-06 05:56 UTC, closed without merging